# Generated by Django 2.0 on 2020-01-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FittingApp', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='season',
            field=models.CharField(default='Fall', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='usage',
            field=models.CharField(default='Casual', max_length=20),
        ),
    ]
