# Generated by Django 2.0 on 2020-01-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FittingApp', '0003_auto_20200119_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Men', 'Male'), ('Women', 'Female')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='season',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Fall', 'Fall'), ('Spring', 'Spring'), ('Winter', 'Winter')], max_length=20),
        ),
    ]
